# Generated by Django 4.1.2 on 2022-10-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendees',
            new_name='volunteers',
        ),
    ]
