# Generated by Django 4.1.2 on 2022-10-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_attendees_event_volunteers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
    ]
