# Generated by Django 4.1.2 on 2022-10-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_rename_volunteers_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web_link',
            field=models.URLField(blank=True, verbose_name='Event Link'),
        ),
    ]
