# Generated by Django 4.1.2 on 2022-10-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='user_uname',
            field=models.CharField(default='test_user', max_length=8),
            preserve_default=False,
        ),
    ]
