# Generated by Django 4.1.2 on 2022-10-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_volunteer_user_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='user_uname',
        ),
    ]
